name: DeployDocs

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    step:
    - uses: actions/checkout@v2
    - name: Deploy doxygen
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: docs/html
          TARGET_FOLDER: Packages/BxUni-ScenarioBuilder/Docments~/Reference/
  